apiVersion: v1
entries:
  keth:
  - apiVersion: v1
    appVersion: 0.0.1
    created: "2020-10-23T21:46:36.839894-06:00"
    description: Kubernetes implementation of the Ethereum protocol
    digest: 96b2ebbc329715896ec310c884ca599f84caa737bfca46eeeb32d8cae14309f9
    home: https://github.com/kube-blockchain/keth
    keywords:
    - blockchain
    - eth
    - ethereum
    - keth
    maintainers:
    - email: sthomas@idis.com
      name: Scott Thomas
    name: keth
    sources:
    - https://github.com/kube-blockchain/keth
    urls:
    - keth-0.0.1.tgz
    version: 0.0.1
generated: "2020-10-23T21:46:36.839011-06:00"
