dnsConfig: {}
env:
  METRICS_PORT: 3001
image:
  repository: ghcr.io/kube-blockchain/keth
  tag: 0.0.3
  pullPolicy: IfNotPresent
  imagePullSecrets: []
prometheus:
  service:
    enabled: false
  serviceMonitor:
    enabled: false

bootnode:
  affinity: {}
  nodeSelector: {}
  overrides:
    fullName: ""
    name: ""
  podAnnotations: {}
  podLabels: {}
  podSecurityContext:
    runAsNonRoot: false
  priorityClassName: ""
  prometheus:
    service:
      enabled: false
    serviceMonitor:
      enabled: false
      interval: "30s"
      namespace:
  rbac:
    create: true
    serviceAccountName:
  replicaCount: 1
  resources: {}
  serviceAccount:
    annotations: {}
    create: true
    name:
  tolerations: []

ethstats:
  affinity: {}
  nodeSelector: {}
  overrides:
    fullName: ""
    name: ""
  podAnnotations: {}
  podLabels: {}
  podSecurityContext:
    runAsNonRoot: false
  priorityClassName: ""
  prometheus:
    service:
      enabled: false
    serviceMonitor:
      enabled: false
      interval: "30s"
      namespace:
  rbac:
    create: true
    serviceAccountName:
  replicaCount: 1
  resources: {}
  serviceAccount:
    annotations: {}
    create: true
    name:
  serviceMonitor:
    enabled: false
    interval: "30s"
    namespace:
  tolerations: []

geth:
  affinity: {}
  nodeSelector: {}
  overrides:
    fullName: ""
    name: ""
  podAnnotations: {}
  podLabels: {}
  podSecurityContext:
    runAsNonRoot: false
  prometheus:
    service:
      enabled: false
    serviceMonitor:
      enabled: false
      interval: "30s"
      namespace:
  priorityClassName: ""
  rbac:
    create: true
    serviceAccountName:
  replicaCount: 1
  resources: {}
  serviceAccount:
    annotations: {}
    create: true
    name:
  serviceMonitor:
    enabled: false
    interval: "30s"
    namespace:
  tolerations: []
