{{- if and .Values.enabled .Values.rbac.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "ethstats.fullname" . }}
  labels: {{ include "ethstats.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "ethstats.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "ethstats.fullname" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
