{{- if .Values.global.ethstats.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{ include "ethstats.labels" . | indent 4 | trim }}
    component: {{ template "ethstats.fullname" . }}
  name: {{ template "ethstats.fullname" . }}
  namespace: {{ $.Release.Namespace }}
spec:
  progressDeadlineSeconds: 600
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      component: {{ template "ethstats.fullname" . }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        component: {{ template "ethstats.fullname" . }}
    spec:
      affinity:
        {{ .Values.affinity | toYaml | indent 8 | trim }}
      containers:
        - env:
            - name: WS_SECRET
              valueFrom:
                secretKeyRef:
                  key: WS_SECRET
                  name: {{ template "ethstats.secretName" . }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          name: ethstats
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      {{- if .Values.extraInitContainers }}
      initContainers:
        {{ .Values.extraInitContainers | toYaml | indent 6 | trim }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector: {{ tpl (toYaml .) $ | indent 8 }}
      {{- end }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName | quote }}
      {{- end }}
      restartPolicy: Always
      schedulerName: default-scheduler
      {{- if .Values.podSecurityContext }}
      securityContext:
        {{ .Values.podSecurityContext | toYaml | indent 8 | trim }}
      {{- end }}
      {{- if .Values.rbac.create }}
      serviceAccountName: {{ template "ethstats.fullname" . }}
      {{- else }}
      serviceAccountName: {{ .Values.rbac.serviceAccountName | quote }}
      {{- end }}
      terminationGracePeriodSeconds: 30
      tolerations:
        {{ .Values.tolerations | toYaml | indent 8 | trim }}
{{- end -}}
