{{- if .Values.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels: {{ include ".labels" . | nindent 4 }}
    component: {{ template ".fullname" . }}
  name: {{ template ".fullname" . }}
  namespace: {{ $.Release.Namespace }}
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      component: {{ template ".fullname" . }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        component: {{ template ".fullname" . }}
    spec:
      {{- with .Values.affinity }}
      affinity: {{ tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      containers:
        - env:
            - name: WS_SECRET
              valueFrom:
                secretKeyRef:
                  key: WS_SECRET
                  name: {{ template ".fullname" . }}
          image: ethereumex/eth-stats-dashboard:latest
          imagePullPolicy: IfNotPresent
          name: ethstats
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      {{- with .Values.nodeSelector }}
      nodeSelector: {{ tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName | quote }}
      {{- end }}
      restartPolicy: Always
      schedulerName: default-scheduler
      {{- if .Values.podSecurityContext }}
      securityContext: {{ toYaml .Values.podSecurityContext | nindent 8 }}
      {{- end }}
      {{- if .Values.rbac.create }}
      serviceAccountName: {{ template ".fullname" . }}
      {{- else }}
      serviceAccountName: {{ .Values.rbac.serviceAccountName | quote }}
      {{- end }}
      terminationGracePeriodSeconds: 30
      {{- with .Values.tolerations }}
      tolerations: {{ tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
{{- end -}}
