{{- if (include ".createSecret" .) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template ".fullname" . }}
  labels: {{ include ".labels" . | nindent 4 }}
type: Opaque
data:
  {{- if and .Values.credentials.webSocketSecret (not .Values.credentials.secretName) }}
  WS_SECRET: {{ .Values.credentials.webSocketSecret | b64enc | quote }}
  {{- end -}}
{{- end }}
