{{- if (include ".createSecret" .) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template ".fullname" . }}
  labels: {{ include ".labels" . | nindent 4 }}
type: Opaque
data:
  {{- if eq .Values.provider "aws" }}
  WS_SECRET: {{ .Values.credentials.webSocketSecret | b64enc | quote }}
  {{- end }}
{{- end }}
