{{- if and .Values.enabled (hasKey .Values.credentials "webSocketSecret") }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template ".fullname" . }}
  labels: {{ include ".labels" . | nindent 4 }}
type: Opaque
data:
  WS_SECRET: {{ .Values.credentials.webSocketSecret | b64enc | quote }}
{{- end }}
