{{- if and .Values.global.ethstats.enabled .Values.credentials.webSocketSecret (not .Values.credentials.secretName) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "ethstats.fullname" . }}
  labels: {{ include "ethstats.labels" . | nindent 4 }}
type: Opaque
data:
  WS_SECRET: {{ .Values.credentials.webSocketSecret | b64enc | quote }}
{{- end }}
