{{- if .Values.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  labels: {{ include ".labels" . | nindent 4 }}
    component: {{ template ".fullname" . }}
  name: {{ template ".fullname" . }}
  namespace: {{ $.Release.Namespace }}
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: http
  selector:
    component: {{ template ".fullname" . }}
  type: ClusterIP
{{- end -}}
