{{- if and .Values.global.ethstats.enabled .Values.rbac.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "ethstats.fullname" . }}
  labels:
    {{ include "ethstats.labels" . | indent 4  | trim}}
  {{- if .Values.rbac.serviceAccountAnnotations }}
  annotations:
    {{ .Values.rbac.serviceAccountAnnotations | toYaml | indent 4 | trim }}
  {{- end }}
{{- end }}
