{{- if .Values.global.ethstats.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  labels: {{ include "ethstats.labels" . | nindent 4 }}
    component: {{ template "ethstats.fullname" . }}
  name: {{ template "ethstats.fullname" . }}
  namespace: {{ $.Release.Namespace }}
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: http
  selector:
    component: {{ template "ethstats.fullname" . }}
  type: ClusterIP
{{- end -}}
