apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keth
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - list
      - patch
      - watch
  - apiGroups:
      - ""
      - events.k8s.io
    resources:
      - events
    verbs:
      - create
