apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keth
rules:
  - apiGroups:
      - kube-blockchain.io
    resources:
      - ethereum
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
      - apps
    resources:
      - configmaps
      - deployments
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
      - events.k8s.io
    resources:
      - events
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - pods/log
    verbs:
      - get
