---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keth
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      containers:
        - image: ghcr.io/kube-blockchain/keth:latest
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
          name: controller
      serviceAccountName: keth
      restartPolicy: Always
