---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: keth
  kubernetes.io/app: keth
resources:
  - cluster-role.yaml
  - cluster-role-binding.yaml
  - crd.yaml
  - deployment.yaml
  - service-account.yaml
