{{- if .Values.global.geth.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels: {{ include "geth.labels" . | nindent 4 }}
    app: geth
  name: {{ template "keth.fullname" . }}
  namespace: {{ $.Release.Namespace }}
data:
  {{- if .Values.genesis }}
  genesis.json: |-
    {{- toPrettyJson .Values.genesis | nindent 4 }}
  {{- else }}
  genesis.json: ''
  {{- end }}
  {{- if .Values.networkId }}
  networkId: {{ .Values.networkId | quote }}
  {{- end }}
{{- end -}}
