{{- if .Values.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels: {{ include "geth.labels" . | nindent 4 }}
    app: geth
  name: {{ template "geth.fullname" . }}
  namespace: {{ $.Release.Namespace }}
data:
  genesis.json: ''
{{- end -}}
