{{- if .Values.global.geth.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{ include "geth.labels" . | indent 4  | trim}}
    app: geth
  name: {{ template "geth.fullname" . }}
  namespace: {{ $.Release.Namespace }}
data:
  {{- if .Values.genesis }}
  genesis.json: |-
    {{ .Values.genesis | toPrettyJson | indent 4 | trim }}
  {{- else }}
  genesis.json: ""
  {{- end }}
  {{- if .Values.networkId }}
  networkId: {{ .Values.networkId | quote }}
  {{- end }}
{{- end }}
