{{- if .Values.global.geth.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels: {{ include "geth.labels" . | nindent 4 }}
    app: geth
  name: {{ template "geth.fullname" . }}
  namespace: {{ $.Release.Namespace }}
data:
  {{- if .Values.genesis }}
  genesis.json: |-
    {{ .Values.genesis | toPrettyJson }}
  {{- end }}
  {{- if .Values.networkId }}
  networkId: {{ .Values.networkId }}
  {{- end }}
{{- end -}}
