{{- if .Values.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels: {{ include ".labels" . | nindent 4 }}
    app: geth
  name: {{ template ".fullname" . }}
  namespace: {{ $.Release.Namespace }}
data:
  genesis.json: ''
{{- end -}}
