{{- if and .Values.global.geth.enabled .Values.rbac.pspEnabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "keth.fullname" . }}-psp
  labels: {{ include "geth.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "keth.fullname" . }}-psp
subjects:
  - kind: ServiceAccount
    name: {{ template "keth.fullname" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
