{{- if and .Values.enabled .Values.account.privateKey .Values.account.secret (not .Values.account.secretName) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template ".fullname" . }}
  labels: {{ include ".labels" . | nindent 4 }}
type: Opaque
data:
  accountPrivateKey: {{ .Values.account.privateKey | b64enc | quote }}
  accountSecret: {{ .Values.account.secret | b64enc | quote }}
{{- end }}
