{{- if and .Values.global.geth.enabled .Values.account.privateKey .Values.account.secret (not .Values.account.secretName) }}
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{ include "geth.labels" . | indent 4  | trim}}
  name: {{ template "geth.fullname" . }}
  namespace: {{ $.Release.Namespace }}
type: Opaque
data:
  accountPrivateKey: {{ .Values.account.privateKey | b64enc | quote }}
  accountSecret: {{ .Values.account.secret | b64enc | quote }}
{{- end }}
