{{- if .Values.global.geth.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  labels: {{ include "geth.labels" . | nindent 4 }}
    component: {{ template "keth.fullname" . }}
  name: {{ template "keth.fullname" . }}
  namespace: {{ $.Release.Namespace }}
spec:
  ports:
    - name: rpc
      port: 8545
      protocol: TCP
      targetPort: 8545
    - name: ws
      port: 8546
      protocol: TCP
      targetPort: 8546
  selector:
    component: {{ template "keth.fullname" . }}
  type: ClusterIP
{{- end -}}
