---
apiVersion: v1
kind: Service
metadata:
  labels: {{ include ".labels" . | nindent 4 }}
    app: geth
    component: {{ template ".fullname" . }}-geth
  name: {{ template ".fullname" . }}-geth
  namespace: {{ .Release.Namespace | quote }}
spec:
  ports:
    - name: rpc
      port: 8545
      protocol: TCP
      targetPort: 8545
    - name: ws
      port: 8546
      protocol: TCP
      targetPort: 8546
  selector:
    component: {{ template ".fullname" . }}-geth
  type: ClusterIP
