{{- if .Values.global.geth.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  {{- if .Values.service.labels }}
  annotations:
    {{ .Values.service.annotations | toYaml | indent 4 | trim }}
  {{- end }}
  labels:
    {{ include "geth.labels" . | indent 4 | trim }}
    {{- if .Values.service.labels }}
    {{ .Values.service.labels | toYaml | indent 4 | trim }}
    {{- end }}
    component: {{ template "geth.fullname" . }}
  name: {{ template "geth.fullname" . }}
  namespace: {{ $.Release.Namespace }}
spec:
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  loadBalancerSourceRanges:
    {{ .Values.service.loadBalancerSourceRanges | toYaml | indent 4 | trim }}
  ports:
    - name: rpc
      port: 8545
      protocol: TCP
      targetPort: 8545
    - name: ws
      port: 8546
      protocol: TCP
      targetPort: 8546
  selector:
    component: {{ template "geth.fullname" . }}
  type: {{ .Values.service.type }}
{{- end -}}
