---
apiVersion: v1
name: keth
version: 0.0.3
appVersion: 0.0.2
description: Kubernetes implementation of the Ethereum protocol
keywords:
  - blockchain
  - eth
  - ethereum
  - keth
home: https://github.com/kube-blockchain/keth
sources:
  - https://github.com/kube-blockchain/keth
maintainers:
  - name: Scott Thomas
    email: sthomas@idis.com
