{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels: {{ include "keth.labels" . | nindent 4 }}
  name: {{ include "keth.fullname" . }}
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - update
{{- if .Values.customResourceManagerDisabled | not }}
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - create
{{- end }}
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  resourceNames:
  - ethereum.kube-blockchain.io
  verbs:
  - get
  - update
- apiGroups:
  - kube-blockchain.io
  resources:
  - ethereum
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kube-blockchain.io
  resources:
  - ethereum/status
  verbs:
  - get
  - update
{{- end -}}
