---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: keth
  namespace: keth
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: keth
  url: ssh://git@github.com/kube-blockchain/keth
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: keth
  namespace: keth
spec:
  interval: 10m0s
  path: ./kube
  prune: true
  sourceRef:
    kind: GitRepository
    name: keth
  validation: client
