---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keth
  namespace: keth
spec:
  chart:
    spec:
      chart: keth
      sourceRef:
        kind: HelmRepository
        name: keth
      version: '*'
  install:
    remediation:
      retries: -1
  interval: 1m0s
  releaseName: dev
  targetNamespace: keth
  upgrade:
    disableWait: true
    remediation:
      retries: -1
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keth-operator
  namespace: keth
spec:
  chart:
    spec:
      chart: keth-operator
      sourceRef:
        kind: HelmRepository
        name: keth
      version: '*'
  install:
    remediation:
      retries: -1
  interval: 1m0s
  releaseName: operator
  targetNamespace: keth
  upgrade:
    disableWait: true
    remediation:
      retries: -1
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: keth
  namespace: keth
spec:
  interval: 1m0s
  timeout: 1m0s
  url: https://kube-blockchain.github.io/keth
