{{- if .Values.global.bootnode.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  {{- if .Values.service.labels }}
  annotations:
    {{ .Values.service.annotations | toYaml | indent 4 | trim }}
  {{- end }}
  labels:
    {{ include "bootnode.labels" . | indent 4 | trim }}
    {{- if .Values.service.labels }}
    {{ .Values.service.labels | toYaml | indent 4 | trim }}
    {{- end }}
    component: {{ template "bootnode.fullname" . }}
  name: {{ template "bootnode.fullname" . }}
  namespace: {{ $.Release.Namespace }}
spec:
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- if .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{ .Values.service.loadBalancerSourceRanges | toYaml | indent 4 | trim }}
  {{- end }}
  ports:
    - name: discovery
      port: 30301
      protocol: UDP
      targetPort: 30301
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    component: {{ template "bootnode.fullname" . }}
  type: {{ .Values.service.type }}
{{- end }}
