---
account:
  secretName: ""
  privateKey: ""
  secret: ""
affinity: {}
args:
  allowinsecureunlock: false
  backtrace: ""
  bloomfilter_size: ""
  bootnodes: ""
  cache: ""
  cache_database: ""
  cache_gc: ""
  cache_noprefetch: false
  cache_preimages: false
  cache_snapshot: ""
  cache_trie: ""
  cache_trie_journal: ""
  cache_trie_rejournal: ""
  config: ""
  datadir: /root/.ethereum
  datadir_ancient: ""
  datadir_minfreedisk: ""
  dev: ""
  dev_period: ""
  discovery_dns: ""
  ethash_cachedir: ""
  ethash_cachesinmem: ""
  ethash_cacheslockmmap: false
  ethash_cachesondisk: ""
  ethash_dagdir: ""
  ethash_dagsinmem: ""
  ethash_dagslockmmap: false
  ethash_dagsondisk: ""
  ethstats: ""
  exec: ""
  exitwhensynced: false
  fakepow: false
  gcmode: ""
  goerli: false
  gpo_blocks: ""
  gpo_maxprice: ""
  gpo_percentile: ""
  graphql: false
  graphql_corsdomain: ""
  graphql_vhosts: ""
  http: true
  http_addr: "0.0.0.0"
  http_api: "admin,debug,web3,eth,txpool,personal,clique,miner,net"
  http_corsdomain: "*"
  http_port: ""
  http_rpcprefix: ""
  http_vhosts: "*"
  identity: ""
  ipcdisable: false
  ipcpath: ""
  jspath: ""
  keystore: ""
  light_egress: ""
  light_ingress: ""
  light_maxpeers: ""
  light_nopruning: false
  light_nosyncserve: false
  light_serve: ""
  lightkdf: false
  log_json: false
  maxpeers: ""
  maxpendpeers: ""
  metrics: false
  metrics_addr: ""
  metrics_expensive: false
  metrics_influxdb: false
  metrics_influxdb_database: ""
  metrics_influxdb_endpoint: ""
  metrics_influxdb_password: ""
  metrics_influxdb_tags: ""
  metrics_influxdb_username: ""
  metrics_port: ""
  mine: false
  miner_etherbase: ""
  miner_extradata: ""
  miner_gaslimit: ""
  miner_gasprice: ""
  miner_gastarget: ""
  miner_notify: ""
  miner_noverify: ""
  miner_recommit: ""
  miner_threads: ""
  nat: ""
  netrestrict: ""
  networkid: ""
  nocompaction: false
  nodekey: ""
  nodekeyhex: ""
  nodiscover: false
  nousb: false
  override_berlin: ""
  password: ""
  pcscdpath: ""
  port: ""
  pprof: false
  pprof_addr: ""
  pprof_blockprofilerate: ""
  pprof_cpuprofile: ""
  pprof_memprofilerate: ""
  pprof_port: ""
  preload: ""
  rinkeby: false
  ropsten: false
  rpc: false
  rpc_allowunprotectedtxs: false
  rpc_gascap: ""
  rpc_txfeecap: ""
  rpcaddr: ""
  rpcapi: ""
  rpccorsdomain: ""
  rpcport: ""
  rpcvhosts: ""
  signer: ""
  snapshot: false
  syncmode: fast
  trace: ""
  txlookuplimit: ""
  txpool_accountqueue: ""
  txpool_accountslots: ""
  txpool_globalqueue: ""
  txpool_globalslots: ""
  txpool_journal: ""
  txpool_lifetime: ""
  txpool_locals: ""
  txpool_nolocals: false
  txpool_pricebump: ""
  txpool_pricelimit: ""
  txpool_rejournal: ""
  ulc_fraction: ""
  ulc_onlyannounce: false
  ulc_servers: ""
  unlock: ""
  usb: false
  v5disc: false
  verbosity: 5
  vm_evm: ""
  vm_ewasm: ""
  vmdebug: false
  vmodule: ""
  whitelist: ""
  ws: true
  ws_addr: "0.0.0.0"
  ws_api: "admin,debug,web3,eth,txpool,personal,clique,miner,net"
  ws_origins: ""
  ws_port: ""
  ws_rpcprefix: ""
  wsaddr: ""
  wsapi: ""
  yolov3: false
ethstats:
  secretName: ""
  webSocketSecret: ""
nodeSelector: {}
overrides:
  fullName: ""
  name: ""
persistence:
  accessMode: ReadWriteOnce
  annotations: {}
  size: 10Gi
  # storageClass: "-"
podAnnotations: {}
podLabels: {}
podSecurityContext:
  runAsNonRoot: false
priorityClassName: ""
prometheus:
  service:
    enabled: false
  serviceMonitor:
    enabled: false
    interval: "30s"
    namespace:
rbac:
  create: true
  pspEnabled: false
  serviceAccountAnnotations: {}
  serviceAccountName: default
replicaCount: 1
resources: {}
serviceAccount:
  annotations: {}
  create: true
  name:
tolerations: []
