---
account:
  secretName: ""
  privateKey: ""
  secret: ""
affinity: {}
enabled: true
ethstats:
  secretName: ""
  webSocketSecret: ""
geth:
  datadir: /root/.ethereum
  ethstats: "${POD_NAME}.${POD_NAMESPACE}:${ETHSTATS_SECRET}@${ETHSTATS_SVC}"
  ropsten: true
  rpc: true
  rpcaddr: "0.0.0.0"
  rpcapi: "admin,debug,web3,eth,txpool,personal,clique,miner,net"
  rpccorsdomain: "*"
  rpcvhosts: "*"
  syncmode: fast
  verbosity: 5
  ws: true
  wsaddr: "0.0.0.0"
  wsapi: "admin,debug,web3,eth,txpool,personal,clique,miner,net"
nodeSelector: {}
overrides:
  fullName: ""
  name: ""
persistence:
  accessMode: ReadWriteOnce
  annotations: {}
  size: 10Gi
  storageClass: "-"
podAnnotations: {}
podLabels: {}
podSecurityContext:
  runAsNonRoot: false
priorityClassName: ""
prometheus:
  service:
    enabled: false
  serviceMonitor:
    enabled: false
    interval: "30s"
    namespace:
rbac:
  create: true
  pspEnabled: false
  serviceAccountAnnotations: {}
  serviceAccountName: default
replicaCount: 1
resources: {}
serviceAccount:
  annotations: {}
  create: true
  name:
tolerations: []
