---
account:
  secretName: ""
  privateKey: ""
  secret: ""
affinity: {}
enabled: true
ethstats:
  secretName: ""
  webSocketSecret: ""
geth:
  datadir: /root/.ethereum
  ethstats: "${POD_NAME}.${POD_NAMESPACE}:${ETHSTATS_SECRET}@${ETHSTATS_SVC}"
  ropsten: true
  rpc: true
  rpcaddr: "0.0.0.0"
  rpcapi: "admin,debug,web3,eth,txpool,personal,clique,miner,net"
  rpccorsdomain: "*"
  rpcvhosts: "*"
  syncmode: fast
  verbosity: 5
  ws: true
  wsaddr: "0.0.0.0"
  wsapi: "admin,debug,web3,eth,txpool,personal,clique,miner,net"
  backtrace: ""
  bloomfilter.size: ""
  bootnodes: ""
  cache: ""
  cache.database: ""
  cache.gc: ""
  cache.noprefetch: ""
  cache.preimages: ""
  cache.snapshot: ""
  cache.trie: ""
  cache.trie.journal: ""
  cache.trie.rejournal: ""
  config: ""
  datadir.ancient: ""
  datadir.minfreedisk: ""
  debug: ""
  dev: ""
  dev.period: ""
  discovery.dns: ""
  ethash.cachedir: ""
  ethash.cachesinmem: ""
  ethash.cacheslockmmap: ""
  ethash.cachesondisk: ""
  ethash.dagdir: ""
  ethash.dagsinmem: ""
  ethash.dagslockmmap: ""
  ethash.dagsondisk: ""
  exec: ""
  exitwhensynced: ""
  fakepow: ""
  gcmode: ""
  goerli: ""
  gpo.blocks: ""
  gpo.maxprice: ""
  gpo.percentile: ""
  graphql: ""
  graphql.corsdomain: ""
  graphql.vhosts: ""
  http: ""
  http.addr: ""
  http.api: ""
  http.corsdomain: ""
  http.port: ""
  http.rpcprefix: ""
  http.vhosts: ""
  identity: ""
  ipcdisable: ""
  ipcpath: ""
  jspath: ""
  keystore: ""
  light.egress: ""
  light.ingress: ""
  light.maxpeers: ""
  light.nopruning: ""
  light.nosyncserve: ""
  light.serve: ""
  lightkdf: ""
  log.json: ""
  mainnet: ""
  maxpeers: ""
  maxpendpeers: ""
  metrics: ""
  metrics.addr: ""
  metrics.expensive: ""
  metrics.influxdb: ""
  metrics.influxdb.database: ""
  metrics.influxdb.endpoint: ""
  metrics.influxdb.password: ""
  metrics.influxdb.tags: ""
  metrics.influxdb.username: ""
  metrics.port: ""
  mine: ""
  miner.etherbase: ""
  miner.extradata: ""
  miner.gaslimit: ""
  miner.gasprice: ""
  miner.gastarget: ""
  miner.notify: ""
  miner.noverify: ""
  miner.recommit: ""
  miner.threads: ""
  nat: ""
  netrestrict: ""
  networkid: ""
  nocompaction: ""
  nodekey: ""
  nodekeyhex: ""
  nodiscover: ""
  nousb: ""
  override.berlin: ""
  pcscdpath: ""
  port: ""
  pprof: ""
  pprof.addr: ""
  pprof.blockprofilerate: ""
  pprof.cpuprofile: ""
  pprof.memprofilerate: ""
  pprof.port: ""
  preload: ""
  rinkeby: ""
  rpc.allowunprotectedtxs: ""
  rpc.gascap: ""
  rpc.txfeecap: ""
  rpcport: ""
  snapshot: ""
  trace: ""
  txlookuplimit: ""
  txpool.accountqueue: ""
  txpool.accountslots: ""
  txpool.globalqueue: ""
  txpool.globalslots: ""
  txpool.journal: ""
  txpool.lifetime: ""
  txpool.locals: ""
  txpool.nolocals: ""
  txpool.pricebump: ""
  txpool.pricelimit: ""
  txpool.rejournal: ""
  ulc.fraction: ""
  ulc.onlyannounce: ""
  ulc.servers: ""
  usb: ""
  v5disc: ""
  vm.evm: ""
  vm.ewasm: ""
  vmdebug: ""
  vmodule: ""
  whitelist: ""
  ws.addr: ""
  ws.api: ""
  ws.origins: ""
  ws.port: ""
  ws.rpcprefix: ""
  yolov3: ""
nodeSelector: {}
overrides:
  fullName: ""
  name: ""
persistence:
  accessMode: ReadWriteOnce
  annotations: {}
  size: 10Gi
  # storageClass: "-"
podAnnotations: {}
podLabels: {}
podSecurityContext:
  runAsNonRoot: false
priorityClassName: ""
prometheus:
  service:
    enabled: false
  serviceMonitor:
    enabled: false
    interval: "30s"
    namespace:
rbac:
  create: true
  pspEnabled: false
  serviceAccountAnnotations: {}
  serviceAccountName: default
replicaCount: 1
resources: {}
serviceAccount:
  annotations: {}
  create: true
  name:
tolerations: []
