---
account:
  # secretName:
  privateKey: ""
  secret: ""
affinity: {}
enabled: true
ethstats:
  # secretName:
  webSocketSecret: ""
nodeSelector: {}
overrides:
  fullName: ""
  name: ""
persistence:
  accessMode: ReadWriteOnce
  annotations: {}
  size: 10Gi
  # storageClass: "-"
podAnnotations: {}
podLabels: {}
podSecurityContext:
  runAsNonRoot: false
priorityClassName: ""
prometheus:
  service:
    enabled: false
  serviceMonitor:
    enabled: false
    interval: "30s"
    namespace:
rbac:
  apiVersion: v1
  create: true
  pspEnabled: false
  serviceAccountAnnotations: {}
  serviceAccountName: default
replicaCount: 1
resources: {}
serviceAccount:
  annotations: {}
  create: true
  name:
tolerations: []
