---
apiVersion: v1
kind: Service
metadata:
  labels: {{ include "keth.labels" . | nindent 4 }}
  name: {{ include "keth.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "keth.name" . }}
  ports:
  - protocol: TCP
    port: {{ .Values.env.METRICS_PORT }}
    name: prometheus
    targetPort: prometheus
