---
affinity: {}
credentials:
  secretName: ""
  webSocketSecret: ""
enabled: true
nodeSelector: {}
overrides:
  fullName: ""
  name: ""
podAnnotations: {}
podLabels: {}
podSecurityContext:
  runAsNonRoot: false
priorityClassName: ""
prometheus:
  service:
    enabled: false
  serviceMonitor:
    enabled: false
    interval: "30s"
    namespace:
rbac:
  create: true
  pspEnabled: false
  serviceAccountAnnotations: {}
  serviceAccountName: default
replicaCount: 1
resources: {}
serviceAccount:
  annotations: {}
  create: true
  name:
tolerations: []
