---
affinity: {}
credentials:
  secretName: ""
  webSocketSecret: ""
extraInitContainers: ""
image:
  pullPolicy: IfNotPresent
  pullSecrets: []
  registry: docker.io
  repository: ethereumex/eth-stats-dashboard
  tag: latest
ingress:
  annotations: {}
  className: ""
  enabled: false
  extraLabels: {}
  extraPaths: []
  hosts: []
  tls: []
init:
  resources: {}
metrics:
  metricsPort: false
  serviceMonitor:
    enabled: false
    interval: "30s"
    labels: {}
    namespace:
nodeSelector: {}
overrides:
  fullName: ""
  name: ""
podAnnotations: {}
podLabels: {}
podSecurityContext:
  fsGroup: 1000
priorityClassName: ""
prometheus:
  service:
    enabled: false
  serviceMonitor:
    enabled: false
    interval: "30s"
    namespace:
rbac:
  create: true
  serviceAccountAnnotations: {}
  serviceAccountName: default
replicaCount: 1
resources:
  requests:
    memory: "64Mi"
    cpu: "250m"
  limits:
    memory: "128Mi"
    cpu: "500m"
schedulerName: default-scheduler
securityContext:
  capabilities:
    drop:
      - ALL
  runAsNonRoot: true
  runAsUser: 1000
service:
  annotations: {}
  labels: {}
  loadBalancerIP: ""
  loadBalancerSourceRanges: []
  port: 80
  type: ClusterIP
serviceAccount:
  annotations: {}
  create: true
  name:
tolerations: []

global:
  ethstats:
    enabled: true
