dnsConfig: {}
env:
  METRICS_PORT: 3001
image:
  repository: ghcr.io/kube-blockchain/keth
  tag: 0.0.3
  pullPolicy: IfNotPresent
  imagePullSecrets: []
overrides:
  fullName: ""
  name: ""
prometheus:
  service:
    enabled: false
  serviceMonitor:
    enabled: false

bootnode:
  affinity: {}
  enabled: true
  nodeSelector: {}
  overrides:
    fullName: ""
    name: ""
  podAnnotations: {}
  podLabels: {}
  podSecurityContext:
    runAsNonRoot: false
  priorityClassName: ""
  prometheus:
    service:
      enabled: false
    serviceMonitor:
      enabled: false
      interval: "30s"
      namespace:
  rbac:
    apiVersion: v1beta1
    create: true
    pspEnabled: false
    serviceAccountAnnotations: {}
    serviceAccountName: default
  replicaCount: 1
  resources: {}
  serviceAccount:
    annotations: {}
    create: true
    name:
  tolerations: []

ethstats:
  affinity: {}
  credentials:
    # secretName:
    webSocketSecret: ""
  enabled: true
  nodeSelector: {}
  overrides:
    fullName: ""
    name: ""
  persistence:
    accessMode: ReadWriteOnce
    annotations: {}
    size: 10Gi
    # storageClass: "-"
  podAnnotations: {}
  podLabels: {}
  podSecurityContext:
    runAsNonRoot: false
  priorityClassName: ""
  prometheus:
    service:
      enabled: false
    serviceMonitor:
      enabled: false
      interval: "30s"
      namespace:
  rbac:
    apiVersion: v1beta1
    create: true
    pspEnabled: false
    serviceAccountAnnotations: {}
    serviceAccountName: default
  replicaCount: 1
  resources: {}
  serviceAccount:
    annotations: {}
    create: true
    name:
  serviceMonitor:
    enabled: false
    interval: "30s"
    namespace:
  tolerations: []

geth:
  account:
    # secretName:
    privateKey: ""
    secret: ""
  affinity: {}
  enabled: true
  ethstats:
    # secretName:
  nodeSelector: {}
  overrides:
    fullName: ""
    name: ""
  podAnnotations: {}
  podLabels: {}
  podSecurityContext:
    runAsNonRoot: false
  prometheus:
    service:
      enabled: false
    serviceMonitor:
      enabled: false
      interval: "30s"
      namespace:
  priorityClassName: ""
  rbac:
    apiVersion: v1beta1
    create: true
    pspEnabled: false
    serviceAccountAnnotations: {}
    serviceAccountName: default
  replicaCount: 1
  resources: {}
  serviceAccount:
    annotations: {}
    create: true
    name:
  serviceMonitor:
    enabled: false
    interval: "30s"
    namespace:
  tolerations: []
