dnsConfig: {}
env:
  METRICS_PORT: 3001
prometheus:
  service:
    enabled: false
  serviceMonitor:
    enabled: false

overrides:
  fullName: ""
  name: ""
tests:
  enabled: false

bootnode:
  affinity: {}
  nodeSelector: {}
  overrides:
    fullName: ""
    name: ""
  podAnnotations: {}
  podLabels: {}
  podSecurityContext:
    runAsNonRoot: false
  priorityClassName: ""
  prometheus:
    service:
      enabled: false
    serviceMonitor:
      enabled: false
      interval: "30s"
      namespace:
  rbac:
    create: true
    pspEnabled: false
    serviceAccountAnnotations: {}
    serviceAccountName: default
  replicaCount: 1
  resources: {}
  schedulerName: default-scheduler
  serviceAccount:
    annotations: {}
    create: true
    name:
  tolerations: []

ethstats:
  affinity: {}
  credentials:
    secretName: ""
    webSocketSecret: ""
  genesis: {}
  nodeSelector: {}
  overrides:
    fullName: ""
    name: ""
  persistence: 
    accessMode: ReadWriteOnce
    annotations: {}
    size: 10Gi
    storageClass: "-"
  podAnnotations: {}
  podLabels: {}
  podSecurityContext:
    runAsNonRoot: false
  priorityClassName: ""
  prometheus:
    service:
      enabled: false
    serviceMonitor:
      enabled: false
      interval: "30s"
      namespace:
  rbac:
    create: true
    pspEnabled: false
    serviceAccountAnnotations: {}
    serviceAccountName: default
  replicaCount: 1
  resources: {}
  schedulerName: default-scheduler
  serviceAccount:
    annotations: {}
    create: true
    name:
  serviceMonitor:
    enabled: false
    interval: "30s"
    namespace:
  tolerations: []

geth:
  account:
    secretName: ""
    privateKey: ""
    secret: ""
  args:
    http: true
    http_addr: "0.0.0.0"
    http_api: "admin,debug,web3,eth,txpool,personal,ethash,miner,net"
    http_corsdomain: "*"
    http_vhosts: "*"
    nousb: true
    syncmode: fast
    verbosity: 3
    ws: true
    ws_addr: "0.0.0.0"
    ws_api: "admin,debug,web3,eth,txpool,personal,ethash,miner,net"
  affinity: {}
  ethstats:
    secretName: ""
    webSocketSecret: ""
  networkId: ""
  nodeSelector: {}
  overrides:
    fullName: ""
    name: ""
  podAnnotations: {}
  podLabels: {}
  podSecurityContext:
    runAsNonRoot: false
  prometheus:
    service:
      enabled: false
    serviceMonitor:
      enabled: false
      interval: "30s"
      namespace:
  priorityClassName: ""
  rbac:
    create: true
    pspEnabled: false
    serviceAccountAnnotations: {}
    serviceAccountName: default
  replicaCount: 1
  resources: {}
  schedulerName: default-scheduler
  serviceAccount:
    annotations: {}
    create: true
    name:
  serviceMonitor:
    enabled: false
    interval: "30s"
    namespace:
  tolerations: []

global:
  bootnode:
    enabled: true
  ethstats:
    enabled: true
  geth:
    enabled: true
