---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    component: {name}-ethstats
  name: {name}-ethstats
  namespace: {namespace}
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      component: {name}-ethstats
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        component: {name}-ethstats
    spec:
      containers:
        - env:
            - name: WS_SECRET
              valueFrom:
                secretKeyRef:
                  key: WS_SECRET
                  name: {ethstatsSecret}
          image: ethereumex/eth-stats-dashboard:latest
          imagePullPolicy: IfNotPresent
          name: ethstats
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
          resources: {{}}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {{}}
      terminationGracePeriodSeconds: 30
