---
apiVersion: v1
kind: Service
metadata:
  labels:
    component: {name}-geth-api
  name: {name}
  namespace: {namespace}
spec:
  ports:
  - name: rpc
    port: 8545
    protocol: TCP
    targetPort: 8545
  - name: ws
    port: 8546
    protocol: TCP
    targetPort: 8546
  selector:
    component: {name}-geth-api
  type: ClusterIP
