---
apiVersion: v1
kind: Service
metadata:
  labels:
    component: {name}-bootnode
  name: {name}-bootnode
  namespace: {namespace}
spec:
  ports:
    - name: discovery
      port: 30301
      protocol: UDP
      targetPort: 30301
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    component: {name}-bootnode
  sessionAffinity: None
  type: ClusterIP
