---
apiVersion: v1
kind: Service
metadata:
  labels:
    component: {name}-ethstats
  name: {name}-ethstats
  namespace: {namespace}
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: http
  selector:
    component: {name}-ethstats
  type: ClusterIP
