---
affinity: {}
extraInitContainers: ""
image:
  pullPolicy: IfNotPresent
  pullSecrets: []
  registry: docker.io
  repository: ethereum/client-go
  tag: alltools-v1.10.1
ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: example.local
      paths:
        - path: /
  tls: []
nodeSelector: {}
overrides:
  fullName: ""
  name: ""
podAnnotations: {}
podLabels: {}
podSecurityContext:
  fsGroup: 1000
priorityClassName: ""
prometheus:
  service:
    enabled: false
  serviceMonitor:
    enabled: false
    interval: "30s"
    namespace:
rbac:
  create: true
  pspEnabled: false
  serviceAccountAnnotations: {}
  serviceAccountName: default
replicaCount: 1
resources: {}
securityContext:
  capabilities:
    drop:
    - ALL
  runAsNonRoot: true
  runAsUser: 1000
serviceAccount:
  annotations: {}
  create: true
  name:
tolerations: []
