{{- if and .Values.global.geth.enabled .Values.ingress.enabled -}}
{{- $fullName := include "keth.fullname" . -}}
{{- $httpPort := .Values.httpPort -}}
{{- $ingressPath := .Values.ingress.path -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  {{- if .Values.ingress.annotations }}
  annotations:
    {{ .Values.ingress.annotations | toYaml | indent 4 | trim }}
  {{- end }}
  labels:
    {{ include "geth.labels" . | indent 4  | trim}}
    component: {{ template "geth.fullname" . }}
  name: {{ template "geth.fullname" . }}
  namespace: {{ $.Release.Namespace }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
  {{- if .ingressPath }}
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . }}
        {{- end }}
        secretName: {{ .secretName }}
        {{- end }}
    {{- else }}
    {{ .Values.ingress.tls | toYaml | indent 4 }}
    {{- end }}
  {{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
    {{- if $ingressPath }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $httpPort }}
    {{- else }}
    - host: {{ .host }}
      http:
        paths:
        {{- range .paths }}
          - path: {{ .path }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ .servicePort | default $httpPort }}
        {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
