{{- if and .Values.global.geth.enabled ( or .Values.prometheus.serviceMonitor.enabled .Values.prometheus.service.enabled ) }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "geth.fullname" . }}-metrics
  labels:
    {{ include "geth.labels" . | indent 4 | trim }}
  {{- if .Values.prometheus.service.annotations }}
  annotations:
    {{ .Values.prometheus.service.annotations | toYaml | indent 4 | trim }}
  {{- end }}
spec:
  selector:
    app.kubernetes.io/name: {{ template "geth.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    {{- if .Values.prometheus.metricsPort }}
    - name: metrics
      port: {{ .Values.prometheus.metricsPort }}
      targetPort: {{ .Values.prometheus.metricsPort }}
    {{- else }}
    - name: http
      port: {{ .Values.host.port }}
      targetPort: {{ .Values.host.port }}
    {{- end }}
    protocol: TCP
{{ end }}
