{{- if (include "keth-operator.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  labels: {{ include "keth-operator.labels" . | nindent 4 }}
  name: {{ template "keth-operator.fullname" . }}
type: Opaque
data: {}
{{- end }}
