{{- if .Values.serviceAccount.create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  {{- if .Values.serviceAccount.annotations }}
  annotations: {{ toYaml .Values.serviceAccount.annotations | nindent 4 }}
  {{- end }}
  labels: {{ include "keth-operator.labels" . | nindent 4 }}
  name: {{ include "keth-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
{{- end -}}
