name: Release Docker Image
on:
  push:
    branches:
      - main
    paths:
      - images/keth/**
    tags:
      - v*
env:
  IMAGE_NAME: keth
jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2
      - name: Test and build image
        run: |
          docker build images/keth/. --tag "${IMAGE_NAME}"
      - name: Log into the container registry
        run: |
          echo "${{ secrets.CR_PAT }}" |\
          docker login https://ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Push the image to the container registry
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          [ "$VERSION" == "main" ] && VERSION=latest
          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
