name: Release Docker Image - keth-helm-test
on:
  push:
    branches:
      - main
    paths:
      - images/keth-helm-test/**
    tags:
      - v*
env:
  IMAGE_NAME: keth-helm-test
jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2
      - name: Test and build image
        run: |
          docker build images/keth-helm-test/. --tag "${IMAGE_NAME}"
      - name: Log into the container registry
        run: |
          echo "${{ secrets.CR_PAT }}" |\
          docker login https://ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Push the image to the container registry
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          if [[ "${{ github.ref }}" == "refs/tags/"* ]]; then
            VERSION=$(echo $VERSION | sed -e 's/^v//')
          fi

          if [[ "$VERSION" != "main" ]]; then
            docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
            docker push $IMAGE_ID:$VERSION
          fi

          docker tag $IMAGE_NAME $IMAGE_ID:latest
          docker push $IMAGE_ID:latest
