{{- if and .Values.global.bootnode.enabled .Values.rbac.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "bootnode.fullname" . }}
  labels:
    {{ include "bootnode.labels" . | indent 4 | trim }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "bootnode.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "bootnode.fullname" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
