{{- if .Values.global.bootnode.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{ include "bootnode.labels" . | indent 4 | trim }}
    component: {{ template "bootnode.fullname" . }}
  name: {{ template "bootnode.fullname" . }}
  namespace: {{ $.Release.Namespace }}
spec:
  progressDeadlineSeconds: 600
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      component: {{ template "bootnode.fullname" . }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        component: {{ template "bootnode.fullname" . }}
    spec:
      affinity:
        {{ .Values.affinity | toYaml | indent 8 | trim }}
      containers:
        - args:
            - -c
            - |
              bootnode \
                --nodekey=/etc/bootnode/node.key \
                --verbosity=4
          command:
            - /bin/sh
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          name: bootnode
          ports:
            - containerPort: 30301
              name: discovery
              protocol: UDP
          {{- if .Values.resources }}
          resources:
            {{ .Values.resources | toYaml | indent 12 | trim }}
          {{- end }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /etc/bootnode
              name: data
        - args:
            - -c
            - |
              while true; do
                printf "HTTP/1.1 200 OK\n\nenode://$(bootnode -writeaddress --nodekey=/etc/bootnode/node.key)@$(POD_IP):30301" | nc -l -v -p 80 || break
              done
          command:
            - /bin/sh
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          name: bootnode-server
          ports:
            - containerPort: 80
              protocol: TCP
          {{- if .Values.resources }}
          resources:
            {{ .Values.resources | toYaml | indent 12 | trim }}
          {{- end }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /etc/bootnode
              name: data
      dnsPolicy: ClusterFirst
      initContainers:
        - args:
            - bootnode
            - --genkey=/etc/bootnode/node.key
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          name: genkey
          {{- if .Values.init.resources }}
          resources:
            {{ .Values.init.resources | toYaml | indent 12 | trim }}
          {{- end }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /etc/bootnode
              name: data
        {{- if .Values.extraInitContainers }}
        {{ .Values.extraInitContainers | toYaml | indent 6 | trim }}
        {{- end }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{ .Values.imagePullSecrets | toYaml | indent 8 | trim }}
      {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{ .Values.nodeSelector | toYaml | indent 8 | trim }}
      {{- end }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName | quote }}
      {{- end }}
      restartPolicy: Always
      {{- if .Values.schedulerName }}
      schedulerName: "{{ .Values.schedulerName }}"
      {{- end }}
      {{- if .Values.podSecurityContext }}
      securityContext:
        {{ .Values.podSecurityContext | toYaml | indent 8 | trim }}
      {{- end }}
      {{- if .Values.rbac.create }}
      serviceAccount: {{ template "bootnode.fullname" . }}
      {{- else }}
      serviceAccount: {{ .Values.rbac.serviceAccountName | quote }}
      {{- end }}
      terminationGracePeriodSeconds: 30
      {{- if .Values.tolerations }}
      tolerations:
        {{ .Values.tolerations | toYaml | indent 8 | trim }}
      {{- end }}
      volumes:
        - emptyDir: {}
          name: data
{{- end -}}
