{{- if and .Values.enabled ( or .Values.prometheus.serviceMonitor.enabled .Values.prometheus.service.enabled ) }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "bootnode.fullname" . }}-metrics
  labels: {{ include "bootnode.labels" . | nindent 4 }}
  {{- if .Values.prometheus.service.annotations }}
  annotations:
    {{- toYaml .Values.prometheus.service.annotations | nindent 4 }}
  {{- end }}
spec:
  selector:
    app.kubernetes.io/name: {{ template "bootnode.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    {{- if .Values.prometheus.metricsPort }}
    - name: metrics
      port: {{ .Values.prometheus.metricsPort }}
      targetPort: {{ .Values.prometheus.metricsPort }}
    {{- else }}
    - name: http
      port: {{ .Values.host.port }}
      targetPort: {{ .Values.host.port }}
    {{- end }}
    protocol: TCP
{{ end }}

{{- if and .Values.enabled .Values.prometheus.serviceMonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "bootnode.fullname" . }}
  {{- if .Values.prometheus.serviceMonitor.namespace }}
  namespace: {{ .Values.prometheus.serviceMonitor.namespace }}
  {{- end }}
  labels: {{ include "bootnode.labels" . | nindent 4 }}
    {{- if .Values.prometheus.serviceMonitor.labels }}
    {{- toYaml .Values.prometheus.serviceMonitor.labels | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "bootnode.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    {{- if .Values.prometheus.metricsPort }}
    - port: metrics
    {{- else }}
    - port: http
    {{- end }}
      interval: {{ .Values.prometheus.serviceMonitor.interval }}
      path: /metrics
{{- end -}}
{{- end -}}
