---
apiVersion: v1
kind: Service
metadata:
  labels: {{ include ".labels" . | nindent 4 }}
    component: {{ template ".fullname" . }}-bootnode
  name: {{ template ".fullname" . }}-bootnode
  namespace: {{ .Release.Namespace | quote }}
spec:
  ports:
    - name: discovery
      port: 30301
      protocol: UDP
      targetPort: 30301
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    component: {{ template ".fullname" . }}-bootnode
  sessionAffinity: None
  type: ClusterIP
