{{- if .Values.global.bootnode.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{ include "bootnode.labels" . | indent 4 | trim }}
    component: {{ template "bootnode.fullname" . }}
  name: {{ template "bootnode.fullname" . }}
  namespace: {{ $.Release.Namespace }}
spec:
  ports:
    - name: discovery
      port: 30301
      protocol: UDP
      targetPort: 30301
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    component: {{ template "bootnode.fullname" . }}
  sessionAffinity: None
  type: ClusterIP
{{- end -}}
