{{- if and .Values.enabled .Values.rbac.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "bootnode.fullname" . }}
  labels: {{ include "bootnode.labels" . | nindent 4 }}
  {{- if .Values.rbac.serviceAccountAnnotations }}
  annotations: {{ toYaml .Values.rbac.serviceAccountAnnotations | nindent 4 }}
  {{- end }}
{{- end }}
